---

- hosts: all

  vars:
      host: "{{ inventory_hostname }}"
      repo_url: "git@github.com:mpff/punpun.me.git"
      site_dir: "/home/{{ ansible_user }}/sites/{{ host }}"
      local_dir: "{{ inventory_dir }}/.."

  tasks:

    - name: install required packages
      apt:
          pkg=nginx,git,python3.6,python3.6-venv 
          state=present
      become: yes

    - name: create site directory 
      file:
          path: "{{ site_dir }}"
          state: directory

    - name: get local git checkout
      local_action: command chdir={{ local_dir }} git log --pretty=format:"%H" -n 1
      register: local_commit

    - name: get source code
      git:
        dest: "{{ site_dir }}"
        repo: "{{ repo_url }}"
        version: "{{ local_commit.stdout }}"

    - name: Install requirements
      pip: 
        requirements: "{{ site_dir }}/requirements.txt"
        virtualenv: "{{ site_dir }}/virtualenv"
        virtualenv_command: python3.6 -m venv

    - name: check if dotenv exists
      stat:
          path: "{{ site_dir }}/.env"
      register: envpath


    - name: allow long hostnames in nginx
      lineinfile:
          dest=/etc/nginx/nginx.conf
          regexp='(\s+)#? ?server_names_hash_bucket_size'
          backrefs=yes
          line='\1server_names_hash_bucket_size 64;'
      become: yes

    - name: add nginx config to sites-available
      template: src=./nginx.conf.j2 dest=/etc/nginx/sites-available/{{ host }}
      notify:
          - restart nginx
      become: yes

    - name: add symlink in nginx sites-enabled
      file:
          src=/etc/nginx/sites-available/{{ host }}
          dest=/etc/nginx/sites-enabled/{{ host }}
          state=link
      notify:
          -restart nginx
      become: yes

    - name: write gunicorn service script
      template:
          src=./gunicorn.service.j2
          dest=/etc/systemd/system/gunicorn-{{ host }}.service
      notify:
          - restart gunicorn
      become: yes

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart gunicorn
      systemd:
          name=gunicorn-{{ host }}
          daemon_reload=yes
          enabled=yes
          state=restarted

